Repository muesli/duf, pull requests merged in 2020-10, with the labels that each got.

#38 Add --hide-fs to hide specific fs types
  main.go
Labels: enhancement

#53 Add linter workflow
  .github/workflows/lint.yml
  .golangci.yml
Labels: enhancement

#55 Add FreeBSD package to README
  README.md
Labels: documentation

#54 Add style flag
  main.go
  table.go
Labels: enhancement

#63 [Windows] Fix broken table structure for non-unicode code page
  go.mod
  main.go
  style_unix.go
  style_windows.go
Labels: bug

#67 Update screenshot
  duf.png
Labels: documentation

#66 [Linux] fix escaped type & filesystem
  mounts_linux.go
Labels: bug

#72 quiet option to silent all warnings
  main.go
Labels: enhancement
