Repository muesli/duf, pull requests merged in 2022-02, with the labels that each got.

#160 Generate man page when built with 'mango' build-tag
  .github/workflows/manpage.yml
  go.mod
  go.sum
  man.go
Labels: documentation

#145 table: rename inode-related columns to clarify difference between bytes and inodes
  table.go
Labels: enhancement

#163 Add 'ansi' theme that uses the terminal's native 4-bit ANSI colors
  main.go
  themes.go
Labels: enhancement

#154 Fix mountinfo parsing #153
  mounts_linux.go
  mounts_linux_test.go
Labels: bug

#165 Update README badges
  README.md
Labels: documentation
