Repository muesli/duf, pull requests merged in 2025-08, with the labels that each got.

#265 Add Fedora to the installation instructions
  README.md
Labels: documentation

#267 Add Solus to repo packages installation instructions
  README.md
Labels: documentation

#303 ci: deadcode linter is no longer used
  filesystems_linux.go
  mounts.go
Labels: dependencies

#209 Fix the duplicate of the result list
  main.go
Labels: enhancement
